/****** Object:  Table [dbo].[NPC]    Script Date: 5/15/2020 1:01:18 AM ******/
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[NPC](
	[NPC_ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[CR] [int] NULL,
	[StatID] [int] NOT NULL,
	[CampaignID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[NPC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[NPC] ADD  DEFAULT ((0)) FOR [CR]

ALTER TABLE [dbo].[NPC]  WITH CHECK ADD  CONSTRAINT [FK_NPC_Campaign] FOREIGN KEY([CampaignID])
REFERENCES [dbo].[Campaign] ([CampaignID])
ON UPDATE CASCADE
ON DELETE CASCADE

ALTER TABLE [dbo].[NPC] CHECK CONSTRAINT [FK_NPC_Campaign]

ALTER TABLE [dbo].[NPC]  WITH CHECK ADD  CONSTRAINT [FK_NPC_StatBlock] FOREIGN KEY([StatID])
REFERENCES [dbo].[StatBlock] ([StatID])

ALTER TABLE [dbo].[NPC] CHECK CONSTRAINT [FK_NPC_StatBlock]



